### ISSUE TITLE
Can't add new shipments

### ISSUE THREAD

**Issue by MTrab** [custom-cards/aftership-card#8]
**Version of the cusom_component**
1.1.0

**Describe the bug**
When filling in the fields on the card, with description and tracking number, and hits the + sign, nothing more happens.
No packages are added

**log**

Nothing in the logs

**Comment by MTrab** [comment]
Still an issue

**Comment by MwC-Trexx** [comment]
still an issue

**Comment by fribse** [comment]
It's the same I see. It works when it's empty, when a shipment is added either through the aftership card or directly in the aftership website, the card goes invisible. I can see the tracked item in the aftership sensor, but the card disappears.

**Comment by iantrich** [comment]
@MTrab changes are not immediate, it takes time for the integration to update.
@fribse your issue sounds like it is related to a null tracking location. That should be fixed in 1.1.1

**Comment by MTrab** [comment]
> changes are not immediate, it takes time for the integration to update

But months?!
The tracking numbers added in July are still not added.

**Comment by iantrich** [comment]
Does it work if you use the integration service directly?

**Comment by MTrab** [comment]
Yes

**Comment by Toukassay** [comment]
Yup, same for me and can't even confirm it works through service directly. I'm still waiting to see the parcel in AfterShip to confirm.

**Comment by iantrich** [comment]
Any errors in your logs?

**Comment by Toukassay** [comment]
> Any errors in your logs?

Hum, in fact it's getting worse so maybe something gone wrong, I dunno, I haven't touch anything since it worked (minus the fact that I couldn't add parcels).

Here's my error : 

`aftership: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 291, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 417, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/aftership/sensor.py", line 184, in async_update
    else track["checkpoints"][-1]
IndexError: list index out of range`

**Comment by Toukassay** [comment]
Seems more an issue on the aftership plugin itself, sorry. I can clearly see : 
`aftership: Error on device update!
20:15 components/aftership/sensor.py (ERROR)`

**Comment by MTrab** [comment]
Somehow it now works after upgrading to 1.1.3 of the card.
